name: Multi Job
on:
  workflow_dispatch:
jobs:
  job-1-build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Build job successfully executed!"

  job-2-test:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: echo "Test job successfully executed!"

  job-3-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Deploy job successfully executed!"

      
